---
- name: Ensure apt updated
  become: true
  tags:
    - common
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Ensure common components
  become: true
  tags:
    - common
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - unzip
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Upgrade all packages to the latest version
  become: true
  when: upgrade_software|bool
  tags:
    - common
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Ensure auto-update cron job
  become: true
  tags:
    - common
  ansible.builtin.cron:
    name: auto update
    hour: "4"
    minute: "0"
    job: sudo -s eval 'apt update && apt upgrade -y'
    state: >-
      {%- if auto_upgrade|bool -%}
      present
      {%- else -%}
      absent
      {%- endif -%}
