---
- name: Ensure time zone
  become: yes
  when: time_zone is defined
  tags:
    - common
  timezone:
    name: "{{ time_zone }}"

- name: Ensure python3 is default interpreter
  become: yes
  when: python3_default_interpreter|bool
  tags:
    - common
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3
    priority: 1

- when: lower(ansible_distribution) == "ubuntu"
  tags:
    - common
  include_tasks: ubuntu.yml
