---
- name: Ensure common components
  become: yes
  tags:
    - common
  apt:
    name:
      - python3
      - python3-pip
      - unzip
      - ntp
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Ensure python3 is default interpreter
  become: yes
  when: python3_default_interpreter|bool
  tags:
    - common
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3
    priority: 1

- name: Ensure time zone
  become: yes
  when: time_zone is defined
  tags:
    - common
  timezone:
    name: "{{ time_zone }}"

- name: Upgrade all packages to the latest version
  become: yes
  when: upgrade_software|bool
  tags:
    - common
  apt:
    name: "*"
    state: latest

- name: Ensure auto-update cron job
  become: yes
  when: auto_upgrade|bool
  tags:
    - common
  cron:
    name: auto update
    hour: "4"
    minute: "0"
    job: sudo -s eval 'apt update && apt upgrade -y && reboot'
